### ISSUE TITLE
icon size

### ISSUE THREAD

**Issue by fibo** [Templarian/MaterialDesign-React#10]
Hi, why the icon size is multiplied by 1.5 ?

I refer to this snippet:

```javascript
  const width = typeof size === "string" ? size : `${size * 1.5}rem`;
```

I am wrapping `@mdi/react` icon to add `isSmall`, `isLarge` props: I expected that size would be passed as is.

**Comment by Templarian** [comment]
@fibo We make the assumption that most users use a base rem size of `16px`. `16` * `1.5` = `24px` the native 1:1 size for people on older screens this should look best.

You can also pass a string to the `size`. So you could put any value you want. `size={'1.5em'}` for example.

Hopefully that reasoning makes sense. It's mostly to accommodate 95% of users, but allows the 5% to use a string.

**Comment by Templarian** [comment]
So in your wrapper, simply put ``size={`${size}rem`}``, is what I mean.

**Comment by Templarian** [comment]
Chatting with the team about this, we're going to remove the default setting of 1 and make it unset.

**Comment by Templarian** [comment]
Okay, we've decided to bundle this breaking change into `v1.0.0` along side the release of `<Stack/>` component that will be bundled with `<Icon/>`.

**Comment by fibo** [comment]
Thanks for the answer and support, I also opted for passing a string.

**Comment by Templarian** [comment]
Since you're passing a string it will continue to work the same after the changes go out for v1.0.0. Your feedback along with 2 others convinced me we should change the default functionality in the final release, so thanks!

**Comment by Templarian** [comment]
@fibo By the way `v1.0.0` released with this change (and lots of other updates). 😺
