### ISSUE TITLE
Release v1.0.0 on NPM

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign-React#12]
Testing for the new updated codebase is merged into master. 

Only thing left is to do a NPM release. This includes 1 breaking change.

- The `size` prop no longer defaults to `1`, so the `width: 1.5rem` size will no longer show by default.
  - `.container-here svg { width: 1.5rem; }`

**Comment by Templarian** [comment]
Done!

Please let me know if you see any regressions other than listed above @azdanov. I've know a few others that will be updating their versions.

**Comment by andrewjrhill** [comment]
@Templarian - Out of curiosity, do you recall why the default for the `size` prop was switch to `null`?

I recently dropped this into a project I am working on that uses a lot of icons and find myself having to pick between either extending your component with a wrapper that has a default size or adding `size={1}` to every icon we drop into the project.

Either way, it adds an additional "thing to remember" to the project and seemingly reduces scalability as it is an additional learning step for future devs who join our team.

**Comment by Templarian** [comment]
@andrewjrhill Short answer is we want you to define icon sizes in CSS. As shown in the notes above you can get the desired icon size by appen

```css
.container svg { width: 1.5rem }
```

Long answer is that `@mdi/react` is made for more icon packs than just `@mdi/js`, you can also use the 'Simple Icons` brand package (since we decided the maintenance burden to support branding was outside our scope a few years back).

**Comment by andrewjrhill** [comment]
@Templarian - Thanks for the response 👍  

Great work by the way. This is a really nice library.
