### ISSUE TITLE
Counter Clockwise Spin Bug

### ISSUE THREAD

**Issue by lbtien1990** [Templarian/MaterialDesign-React#22]
I try but it still not spin. Here is this issue: [https://stackblitz.com/edit/react-mdi-spin](https://stackblitz.com/edit/react-mdi-spin)

**Comment by Templarian** [comment]
@lbtien1990 Completely spaced on fixing this. It's in `1.2.1`.

Thanks for making the test project. Looks like I was always applying `spin` instead of `spin-inverse`. Copying and pasting some logic from above.

Will need to add some better testing around the spin attribute.

**Comment by Templarian** [comment]
Ironically it's the first bullet in #15 from a while back. 🙃
