### ISSUE TITLE
Supplied refs are not propagating to the element

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign-React#24]
Supplying a `ref` to the `<Icon>` element does not work properly, likely because refs need to be forwarded in a way different from all other props.

(Issue likely affects `<Stack>`s as well.)

See: https://reactjs.org/docs/forwarding-refs.html

**Comment by Templarian** [comment]
@goyney Can you have them just npm install the master branch and let me know if it works. I'll do a release with this fix if it's all good.

**Comment by Templarian** [comment]
Fixed this to work with TypeScript. Oversight on the props validation. Let me know this works and I'll push `1.2.0`.

Unit testing isn't possible at this time with Enzyme for refs. I put a placeholder.

**Comment by Templarian** [comment]
@goyney Were they able to test this?

**Comment by goyney** [comment]
Yep, the changes made are good. Feel free to close this upon publish to NPM. :)

**Comment by Templarian** [comment]
Published!
