### ISSUE TITLE
How to dynamically Import Icons?

### ISSUE THREAD

**Issue by AthulNair** [Templarian/MaterialDesign-React#28]
I want to load menu in my application which contains the name of the icon. But it is not showing because not imported. So how to import the icons dynamically and show it in an array

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-React/issues/26

There are several ways to do it, but the issue is you really do not want to include all the icons. It's very heavy. If you only need a few you can follow the advise in the issue above.

**Comment by AthulNair** [comment]
Great solution. Working perfectly. @Templarian

**Comment by Templarian** [comment]
Glad to hear. We'll work on documentation for this as it does come up once in a while.
