### ISSUE TITLE
Support set the `g` element's props

### ISSUE THREAD

**Issue by luyc** [Templarian/MaterialDesign-React#31]
Just like this:

```js
<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
```

**Comment by Templarian** [comment]
What does this visually allow? Like what is the use case for this request?

The optimized paths in MDI don't close paths, so strokes will not always close if you're trying to outline them.

**Comment by luyc** [comment]
@Templarian  Thanks. I used the not optimized icon.
