### ISSUE TITLE
how to tree shake icon?

### ISSUE THREAD

**Issue by popuguytheparrot** [Templarian/MaterialDesign-React#32]
how to tree shake icon? Now loading all icons from package

**Comment by Templarian** [comment]
React's toolchain has tree shaking built in, so double check you're importing the icons correctly.

`import { mdiAccount } from '@mdi/js';` and not all of them.

**Comment by popuguytheparrot** [comment]
@Templarian its not working. In bundle i see all of icons

**Comment by Templarian** [comment]
Yeah, not sure what's going on. Probably something in the specific project you have.

- Does it happen in the prod build...
- Try to reproduce it in a new blank app.

Not something I'm going to be able to fix as its webpack, roll-up, etc handle this.

**Comment by popuguytheparrot** [comment]
its in production bundle. For example, "@material-ui/icons its tree shakes, but it package not.

**Comment by Templarian** [comment]
That is weird. Search your full project for `@mdi/js` and double check it's only importing them by name.

Beyond try and recreate in a new app.

**Comment by vcardins** [comment]
Still not being able to tree shaking either. Any ideas?

**Comment by petertenhoor** [comment]
Same issue in 2021 with a next.js application. Full 2MB package @mdi/js package ends up in the bundle eventhough I'm only importing a few icons :')
