### ISSUE TITLE
Icon is using deprecated SFC type instead of FunctionComponent type

### ISSUE THREAD

**Issue by jhlav** [Templarian/MaterialDesign-React#37]
Since React Hooks were released, the SFC type for Typescript has been deprecated.  The Type definition says to use the FunctionComponent type instead, so I am opening another PR to simply update that.  This seems to be just a type name change without side effects.

![image](https://user-images.githubusercontent.com/20038091/74604881-4d6f5c80-50e8-11ea-9153-107d4833a004.png)

**Comment by Templarian** [comment]
Resolved.
