### ISSUE TITLE
Dynamic load icons

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [Templarian/MaterialDesign-React#44]
I want to load icons which get icon names from server, is there any way to load/import them dynamically?

For example the user select the icon of a menu item or enter the name of icon.

**Comment by Templarian** [comment]
You would need to read the `meta.json` file from https://github.com/Templarian/MaterialDesign-SVG or `@mdi/svg` package (also stored on the CDN in the root).

Duplicate of #34, please use this issue for further discussion.

The new website under development uses indexedDB solution for rapid loading/storage of icon data and searching. We will be open sourcing this when the site launches. For now there is no pre-made solution.
