### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by nghiant96** [Templarian/MaterialDesign-React#69]
Hello. I am using icon set for my project. It worked fine until. But when I build and run it doesn't work. I am using vite to build the project.
The full text of the error you just encountered is:
 Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Version of me:
  "@mdi/js": "^6.5.95",
  "@mdi/react": "^1.5.0",
  "react": "^17.0.2",

**Comment by Templarian** [comment]
@nghiant96 I just bumped the demo project to v18.0.0 with the existing `1.6.0` package and it seems fine.

Can you please retry with 1.6.0? I'm trying to not bump versions in this until I know there are breaking changes.

**Comment by versoworks** [comment]
@Templarian https://templarian.github.io/@mdi/react/ isn't rendering in Edge & Safari here; console shows 404 returned for a couple of resources.

**Comment by nghiant96** [comment]
> @nghiant96 I just bumped the demo project to v18.0.0 with the existing `1.6.0` package and it seems fine.
> 
> Can you please retry with 1.6.0? I'm trying to not bump versions in this until I know there are breaking changes.
> 
> Updated to v18.0.0 / 1.6.0 https://templarian.github.io/@mdi/react/
i'm fix it 
import Icon from '@mdi/react';
to 
import { Icon } from '@mdi/react';

**Comment by Templarian** [comment]
@versoworks Fixed, forgot to remove the absolute paths. 🤦

**Comment by yf-hk** [comment]
Shall we change the example code in the README?

**Comment by craigrileyuk** [comment]
I just lost hours to this issue thinking it was my build process that was causing the error.

Please add it to the README!

**Comment by HugoGresse** [comment]
As stated in the reference above, this is a bug in Vite : https://github.com/vitejs/vite/issues/2139 
It impact many packages.

**Comment by Mossop** [comment]
> @Templarian i fix it import Icon from '@mdi/react'; to import { Icon } from '@mdi/react';

This doesn't seem to work anymore? I get the following error:

`[vite] Named export 'Icon' not found. The requested module '@mdi/react' is a CommonJS module, which may not support all module.exports as named exports`
