### ISSUE TITLE
add a view-box prop

### ISSUE THREAD

**Issue by ragnaroks** [Templarian/MaterialDesign-React#77]
```jsx
<Icon path="M10 3.5A6.5 6.5 0 0 0 3.5 10A.75.75 0 0 1 2 10a8 8 0 1 1 8 8a.75.75 0 0 1 0-1.5a6.5 6.5 0 1 0 0-13z" spin />

<Icon path="M10 3.5A6.5 6.5 0 0 0 3.5 10A.75.75 0 0 1 2 10a8 8 0 1 1 8 8a.75.75 0 0 1 0-1.5a6.5 6.5 0 1 0 0-13z" spin viewBox="0 0 20 20" />
```
this path designed by `view-box="0 0 20 20"`, could you add a `viewBox` prop to set `view-box` attribute?

**Comment by Templarian** [comment]
The `@mdi/react` package will stay with a fixed viewBox. We're investigating building a more general component for multi-layer iconography that will be published under our org `@pictogrammers/*`.
